### ISSUE TITLE
Test failures with master

### ISSUE THREAD

**Issue by kitterma** [sdgathman/pymilter#1]
When I run the test suite with master, I get the following failures.  Are any of these real?  I think I'm down to pretty much the same failures in my local python3 attempt and I'd like to know how much of this needs fixing too.

Your branch is up-to-date with 'origin/master'.
~/devel/pymilter/pymilter$ python test.py 
.................FE..F..
======================================================================
ERROR: testParseHeader (testutils.AddrCacheTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/~/devel/pymilter/pymilter/testutils.py", line 14, in tearDown
    os.remove(self.fname)
OSError: [Errno 2] No such file or directory: 'test.dat'

======================================================================
FAIL: testParseHeader (testutils.AddrCacheTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/devel/pymilter/pymilter/testutils.py", line 44, in testParseHeader
    self.assertEqual(s,'Last Few Coldplay Album Artworks Available\x00')
AssertionError: '=?UTF-8?B?TGFzdCBGZXcgQ29sZHBsYXkgQWxidW0gQXJ0d29ya3MgQXZhaWxhYmxlAA?=' != 'Last Few Coldplay Album Artworks Available\x00'

======================================================================
FAIL: parseaddr (Milter.utils)
Doctest: Milter.utils.parseaddr
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Milter.utils.parseaddr
  File "~/devel/pymilter/pymilter/Milter/utils.py", line 126, in parseaddr

----------------------------------------------------------------------
File "/home/kitterma/devel/pymilter/pymilter/Milter/utils.py", line 137, in Milter.utils.parseaddr
Failed example:
    parseaddr('Real Name ((comment)) <addr...@example.com>')
Expected:
    ('Real Name', 'addr...@example.com')
Got:
    ('Real Name (comment)', 'addr...@example.com')
----------------------------------------------------------------------
File "~/devel/pymilter/pymilter/Milter/utils.py", line 139, in Milter.utils.parseaddr
Failed example:
    parseaddr('a(WRONG)@b')
Expected:
    ('WRONG', 'a@b')
Got:
    ('WRONG WRONG', 'a@b')

----------------------------------------------------------------------
Ran 23 tests in 0.288s

FAILED (failures=2, errors=1)

**Comment by sdgathman** [comment]
The Real Name parsing bugs are still open.  I think the original is incorrect rfc syntax, but it doesn't matter because we have to parse it anyway.

The parseHeader bugs used to be fixed.  :-(  It is supposed to convert punycode to UTF-8.  Let me see if I can fix it again in python2.

**Comment by sdgathman** [comment]
parseHeader works in python2.6, fails in python2.7.

**Comment by sdgathman** [comment]
Fixed by 3cdf7aa6a5e17d10325c70eff7c09a37fa72b478
and 728ac069cf19930a590ec52ed8b1aefa805c6629
