### ISSUE TITLE
Bug. Typo in setsymlist.

### ISSUE THREAD

**Issue by saletnik** [sdgathman/pymilter#13]
File **Milter/\_\_init\_\_.py:462**
It is 
`return self._ctx.setsmlist(stage,' '.join(a))`
Should be
`return self._ctx.setsymlist(stage,' '.join(a))`

**Comment by sdgathman** [comment]
Yet Another Setsymlist Misspelling.  Thanks - pushed to master.

**Comment by sdgathman** [comment]
It's worth adding test cases for setsymlist even if the test framework doesn't simulate much of it.

**Comment by sdgathman** [comment]
Added test cases and decorator for setsymlist
