### ISSUE TITLE
Strange line

### ISSUE THREAD

**Issue by stillcut** [sdgathman/pymilter#16]
Hello,

I have tested a spf record and I wonder from where the line beginning with D= could be retrieve ?

The TXT records found for your domain are:
D=landerneau.bzh
v=spf1 ip4:90.102.97.217 ip4:90.63.167.244 include:bluecom.fr ~all

Checking to see if there is a valid SPF record.

Found v=spf1 record for mairie-landerneau.fr:
v=spf1 ip4:90.102.97.217 ip4:90.63.167.244 include:bluecom.fr ~all

evaluating...
Results - record processed without error.

**Comment by sdgathman** [comment]
It is a TXT record.  You can retrieve with:
```
$ host -t TXT example.com
```
or use dig:
```
$ dig TXT example.com
```
It is not an SPF record because it does not start with `v=spf1`, so it is ignored by SPF.

**Comment by stillcut** [comment]
Thank you for your answer
