### ISSUE TITLE
Don't put sgmllib back in public namespace

### ISSUE THREAD

**Issue by kitterma** [sdgathman/pymilter#21]
Since sgmllib was removed in Py3K, it would be better not to add it back as an external module.  If you move it from the top level directory into the Milter sub-directory and then apply the attached patch, the public sgmllib will be used for python2 and the internal one will be used for python3.

**Comment by kitterma** [comment]
[internal_sgmllib.txt](https://github.com/sdgathman/pymilter/files/2704448/internal_sgmllib.txt)

**Comment by sdgathman** [comment]
Good idea.  Applied in https://github.com/sdgathman/pymilter/commit/55e5378659e6ed54e72d88f80043942944b38f3f
