### ISSUE TITLE
Use IFDEF for miltermodule.c changes vice add-on patch

### ISSUE THREAD

**Issue by kitterma** [sdgathman/pymilter#22]
Here's a patch that builds with no warnings on both python2.7 and python3.7.
[IFDEF_Integrate-Py3-changes.txt](https://github.com/sdgathman/pymilter/files/2704812/IFDEF_Integrate-Py3-changes.txt)

**Comment by sdgathman** [comment]
If we go the IFDEF route, then it needs additional work to make it more readable.  For instance, I could conditionally #define staticforward static, but that would be confusing to those not acquainted with the code history.  A new macro, maybe PyStatic (but would that conflict with something defined in Py3 API?) would not look py2 API code.

**Comment by sdgathman** [comment]
Eh, I should just apply the patch (it looks like it was derived mechanically from milter.patch) and evolve readability later.

**Comment by sdgathman** [comment]
Ifdef changes pushed with a few readability tweaks in a separate commit.  https://github.com/sdgathman/pymilter/commit/f9b2241ec69d342bd402d0042a763a810ad6961c
