### ISSUE TITLE
BytesIO exception thrown on run with Python3.6-3.7

### ISSUE THREAD

**Issue by josh-richardson** [sdgathman/pymilter#26]
I have a milter with which I've been working with Python 2.7 for the last few months. It's very similar in structure to the example code given in this repository, and I've had no issues with it thus far. Having seen the new versions which has compatibility with Python 3, I've upgraded the milter package along with my code. I've read the issues in relation to the new use of BytesIO where StringIO previously was sufficient, and I believe I've updated all of my own code as necessary. However, upon running my milter I receive the following error, which appears according to the stack trace to be pymilter related:

Traceback (most recent call last):
`File "/home/joshua/.virtualenvs/y4project36/lib/python3.6/site-packages/Milter/__init__.py", line 771, in <lambda>
    milter.set_body_callback(lambda ctx,chunk: ctx.getpriv().body(chunk))
TypeError: '_io.BytesIO' object is not callable
`

I'm wondering if there's something I've missed, or if this is a legitimate issue with the latest release? Thanks!

**Comment by josh-richardson** [comment]
I clearly missed something. Thanks for getting back to me so quick. I'll debug for longer before opening an issue next time.

**Comment by sdgathman** [comment]
Maybe you had a mymilter._body field that was a BytesIO to accumulate the message body - but you forgot the '_' when initializing it?

**Comment by josh-richardson** [comment]
Yes, something very similar happened. Thanks for the pointers.
