### ISSUE TITLE
Back out docs dir commits

### ISSUE THREAD

**Issue by sdgathman** [sdgathman/pymilter#27]
I tried out github pages for hosting documentation, adding a docs dir.  I hate it, since the docs dir is all generated.  I'd like to "back out" the commits that added the docs dir.  I don't even want it in the history.  But I need to study up on git and practice on a clone ...

Since the pymilter docs are mostly generated (DoxyGen), I think I should create a separate repo for github pages.  Or use another documentation host.  I've registered pymilter.org.

**Comment by dkg** [comment]
I've just pushed [a branch called "fix-27"](https://github.com/dkg/pymilter/tree/fix-27), which removes all of the docs dir commits and cleans up the history.

If you want to move to this, you can do that locally.  assuming that your local repository's view of the github repo is named `$GITHUB`, do:

    git remote add dkg https://github.com/dkg/pymilter
    git remote update dkg
    git checkout -B master dkg/fix-27
    git push -f $GITHUB master

i hope this helps!

**Comment by sdgathman** [comment]
I'm more interested in knowing how to do it myself.  At this point, I may just leave the docs dir in the history, it is only 1.4M - much a big deal for a repo.

**Comment by dkg** [comment]
the way i did it was to check out the head, and then do `git rebase -i pymilter-1.0.3` and then delete all of the commits that touched the docs directory.  Once that is done, it's just a push to a new branch.

I'm sure you could do it in a fancier way with something like `git filter-branch`, but for the handful of commits involved, it's much simpler to use the interactive rebase.

Please do consider cleaning it up though, and not just leaving it there -- the history hasn't been tagged yet, and 1.4M *is* a lot for a project whose git history itself is < 3M.

**Comment by sdgathman** [comment]
So these steps:

```
git checkout -B master dkg/fix-27
git push -f $GITHUB master
```
would be the way to "rename" the master branch on sdgathman/pyspf ?

**Comment by sdgathman** [comment]
I've cloned a new working dir, and I'm going to rebase starting with ff6a07e (the last good commit before the docs nonsense), instead of pymilter-1.0.3.  I have another clone of all branches to remember everything as it was - hopefully sufficient backup.

**Comment by sdgathman** [comment]
So, trying the rebase -i.  It *looks* pretty straightforward.  I'm about to pass this on:
```
drop c879608 Attempt to use docs dir for github pages.
drop 4e7cacc Set theme jekyll-theme-minimal
drop 96151e7 Copy sendmail-milter API docs
drop 6277fb4 Set theme jekyll-theme-minimal
pick db74597 Import full path on py3
pick 2915837 Correctly document that body callback chunks are in bytes (#28)
```

**Comment by sdgathman** [comment]
It *looks* like I did it right.  Leaving this open in the hopes that dkg will take a peek.

**Comment by sdgathman** [comment]
Closing this.  Will keep backup copy of repo for a while.

**Comment by dkg** [comment]
looks good to me, @sdgathman -- thanks for taking care of it!
