### ISSUE TITLE
doco nit for miltermodule.c

### ISSUE THREAD

**Issue by qzrrbz** [sdgathman/pymilter#38]
static const char milter_set_flags__doc__[] =
"set_flags(int) -> None\n\
Set flags for filter capabilities; OR of one or more of:\n\
ADDHDRS - filter may add headers\n\
CHGBODY - filter may replace body\n\
CHGFROM - filter may replace body\n\
ADDRCPT - filter may add recipients\n\
DELRCPT - filter may delete recipients\n\
CHGHDRS - filter may change/delete headers";

pretty sure the CHGFROM description is just a copy&paste-o.
perhaps "filter may change the envelope sender"?

**Comment by sdgathman** [comment]
Fixed in bf3108b
