### ISSUE TITLE
Additional deprecation warnings with python3.9 and 3.10

### ISSUE THREAD

**Issue by kitterma** [sdgathman/pymilter#45]
It might be nice if these could be cleaned up for the release so it's more future proof:

creating build/temp.linux-x86_64-3.10
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -O2 -ffile-prefix-map=/build/pymilter-1.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMAX_ML_REPLY=32 -I/usr/include/python3.10 -c miltermodule.c -o build/temp.linux-x86_64-3.10/miltermodule.o -Werror=implicit-function-declaration
miltermodule.c: In function '_generic_wrapper':
miltermodule.c:494:3: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
  494 |   result = PyEval_CallObject(cb, arglist);
      |   ^~~~~~
In file included from /usr/include/python3.10/Python.h:131,
                 from miltermodule.c:49:
/usr/include/python3.10/ceval.h:17:43: note: declared here
   17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
miltermodule.c: In function 'milter_main':
miltermodule.c:902:3: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
  902 |   PyEval_InitThreads();
      |   ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.10/Python.h:131,
                 from miltermodule.c:49:
/usr/include/python3.10/ceval.h:122:37: note: declared here
  122 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~

**Comment by sdgathman** [comment]
This will need #ifdefs to handle python2.7, python3.6 (CentOS-7) and python >= 3.9

**Comment by sdgathman** [comment]
https://github.com/sdgathman/pymilter/commit/102e042a38b5d9d50b9f8b10c8b27f9f2c51949b
