### ISSUE TITLE
Milter.utils.parseaddr fails two doctests

### ISSUE THREAD

**Issue by sdgathman** [sdgathman/pymilter#5]
The parsing is tricky, and has to handle malformed addresses as well as legal ones.  So this has been left hanging.

**Comment by sdgathman** [comment]
I think the way to handle this is a list of regexes.

**Comment by whyscream** [comment]
Both of the failing results are produced by the `rfc822` module, not by the milter code. In both cases the email address is correctly parsed, the issue is with the returned Fullname, which is almost never relevant... I don't see any usage of the `parseaddr` method in the pymilter codebase?

**Comment by sdgathman** [comment]
The full name is actually very important for spam filters - which is why spammers try to obscure it from filters, while still having Outlook display it.  Users think the full name means something, even when the email is unauthenticated.  A bayesian filter will usually learn the obscured fullname, but keyword filters need it unobscured first.

**Comment by sdgathman** [comment]
Here is a snippet from the milter package (yeah, needs renaming) illustrating usage of full name.  Full name is valuable to spammers because it is displayed even when the email itself is not.
```python
    elif lname == 'from' and self.dspam:
      fname,email = parseaddr(val)
      for w in config.spam_words:
        if fname.find(w) >= 0:
          self.log('REJECT: %s: %s' % (name,val))
          self.setreply('550','5.7.1','No soliciting')
          return self.bandomain()
      for w in config.from_words:
        if fname.find(w) >= 0:
          self.log('REJECT: %s: %s' % (name,val))
          self.setreply('550','5.7.1','No soliciting')
          return self.bandomain()
      # check for porn keywords
      lval = fname.lower().strip()
      for w in config.porn_words:
        if lval.find(w) >= 0:
          self.log('REJECT: %s: %s' % (name,val))
          self.setreply('550','5.7.1','Watch your language')
          return self.bandomain()
```

**Comment by tomhendrikx** [comment]
I also read the bug on the rfc822 module referenced in the code. This looks like some sort of pet peeve of yours, which is OK with me, but in the end you're not testing anything that is useful to the milter itself, and no code that is part of the milter currently. You could move this test to the package that actually uses the code, or make the doctest use https://docs.python.org/2.7/library/unittest.html#unittest.expectedFailure so the test suite exists successful.

**Comment by sdgathman** [comment]
One remaining failing test moved to testutils.py and tagged with @expectedFailure.
