### ISSUE TITLE
Please replace bsddb3 by berkeleydb according to upstream deprecation notice

### ISSUE THREAD

**Issue by AkechiShiro** [sdgathman/pymilter#61]
https://github.com/sdgathman/pymilter/blob/1c050807683bfaa24b07cc3d2e39a77d03856ae7/Milter/policy.py#L2

See here : https://github.com/google/nsscache/issues/135

**Comment by AkechiShiro** [comment]
This is causing test failure downstream on my side, thanks for fixing this, hopefully the migration is not too complex for this project.

**Comment by AkechiShiro** [comment]
I can try to make a PR if needed, or if you're too busy, please let me know.

**Comment by sdgathman** [comment]
bsddb3 is used for the sendmail access file.  Has sendmail also moved to berkeleydb ?  Or is the underlying library the same, and this is a python wrapper change?

**Comment by sdgathman** [comment]
I used to use anydbm - I can't remember why I had to go back to bsddb3 explicitly.  Maybe anydbm works again.

**Comment by AkechiShiro** [comment]
Please feel free to let me know when you have tried if `anydbm` works and I'll update the dependencies downstream on my side.

Also I'm not sure if it's just a wrapper change as there were these instruction to migrate old code : 

> You are running Python 3 and you can update your code from bsddb3 library to berkeleydb library:
> 
> The main change you need to be aware is that in berkeleydb keys and values are now bytes, while in bsddb3 they were strings. You would only need to change your code to add or remove type encoding/decoding, depending of how you use the library. The process should be simple. 
>

**Comment by AkechiShiro** [comment]
Was this done in a recent PR, can I close this issue ? @sdgathman

**Comment by sdgathman** [comment]
Have to try combinations of python2.7/3.x and bsddb3/berkeleydb present/absent (anydbm only tries built-in dbms, and bsddb3/berkeleydb was dropped as a builtin).  But you can go ahead and drop bsddb3 as a requirement.  Since berkeleydb is in Fedora 40 and 39, and bsddb3 is deprecated, it really only needs to be tested for EL8.  And I could probably package berkeleydb for EPEL8 if no one else does it first.  (EL7 is near EOL and would just use older pymilter)

Here is the result when neither are present:
```
[stuart@elissa pymilter]$ python3 testpolicy.py
Traceback (most recent call last):
  File "/home/stuart/src/pymilter/Milter/policy.py", line 3, in <module>
    from bsddb3 import db
ModuleNotFoundError: No module named 'bsddb3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stuart/src/pymilter/testpolicy.py", line 5, in <module>
    from Milter.policy import MTAPolicy
  File "/home/stuart/src/pymilter/Milter/policy.py", line 5, in <module>
    from berkeleydb import db
ModuleNotFoundError: No module named 'berkeleydb'
```

**Comment by sdgathman** [comment]
That is the correct result - trying to refresh my memory of how to verify that in a test case.  Maybe just concentrate on correct operation when either is present.  Preference should be given to berkeleydb I think.

**Comment by sdgathman** [comment]
As you suspected, berkeleydb does not work as a simple rename.  Per your hint, will need some key conversion.

**Comment by sdgathman** [comment]
I can't even get berkeleydb to open the access file.  Does not accept db.RD_ONLY.  Looking for docs.

**Comment by sdgathman** [comment]
Nevermind, was opening access, not access.db

**Comment by sdgathman** [comment]
Working now!

**Comment by AkechiShiro** [comment]
Thanks a lot for your work on this !
