### ISSUE TITLE
quarantine() not working?

### ISSUE THREAD

**Issue by buanzo** [sdgathman/pymilter#63]
Hi. I am running self.quarantine("some reason") on the eom() hook. I configured my milter like this, in postfix 3.5.24, python 3.9, pymilter 1.0.5

```bash
# postconf -n|grep milter
milter_default_action = accept
milter_protocol = 6
non_smtpd_milters = $smtpd_milters
smtpd_milters = inet:localhost:10669
```

If I do 'return Milter.DISCARD' it works perfectly, but if I do:

```python
self.quarantine(reason)
return Milter.QUARANTINE
```

then nothing happens. Am I incorrect in calling self.quarantine() ? should I just be returning Milter.QUARANTINE?

**Comment by kitterma** [comment]
That seems reasonable for Postfix and quarantine is one of the values it expects from the milter interface.

**Comment by buanzo** [comment]
Yes, and still I can't make it work. Are you aware of anyone using this?

**Comment by kitterma** [comment]
No.  I believe that you can turn the verbosity of Postfix's logs enough to get the actual milter interface messages in the mail log.

<https://github.com/spacefreak86/pyquarantine-milter> looks like it might use it.

**Comment by buanzo** [comment]
Thanks. I had found and read the source code for pyquarantine-milter earlier today. In fact I did a lot of code reading, even opendmarc's source code. It might be something I'm not seeing. I appreciate your suggestions. I will up verbosity and see what I can find. Will report back here. I also found other mentions in the postfix mailing list in relation to milters, quarantine, which even Mr Wietse Venema replied to... and indeed, the answer was to analyze the traffic between postfix and the milter using tcpdump :) - For the time being, I have resorted to TEMPFAIL.

**Comment by buanzo** [comment]
Sorry for closing ;)

This is how opendmarc does it:

https://github.com/trusteddomainproject/OpenDMARC/blob/9cebf724d601452d1a671ed5331551dbc18df83a/opendmarc/opendmarc.c#L3602

As can be seen, it first calls smfi_quarantine, then seems to ACCEPT... so maybe I need to self.quarantine(reason) then return Milter.ACCEPT

That's actually the only combination I did not try. Will try tomorrow and report back.

**Comment by buanzo** [comment]
OK, This combination works perfectly. Basically, yes, you have to self.quarantine() in eom(), then return Milter.ACCEPT. With that, the email gets put into the postfix (or whatever) HOLD queue.

```python
# ...
    def eom(self):
        if self.sender == "sendertoquarantine@example.com":
            self.quarantine("This reason appears nowhere")
            return Milter.ACCEPT
        else:
            return Milter.CONTINUE
# ...
```

**Comment by sdgathman** [comment]
Have to study the libmilter API.  This does seem mysterious and warrants something in the docs.
